# Regenerate the two fixed text masks used by every platform. No font is bundled.
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$output = [Text.StringBuilder]::new()
[void]$output.AppendLine('// Generated by scripts/windows/Generate-Branding.ps1. Fixed edition text only.')
[void]$output.AppendLine('#pragma once')
[void]$output.AppendLine('#include <cstdint>')
[void]$output.AppendLine('namespace EditionBranding::Assets {')
$editionName = -join ([char[]]@(0x4e38, 0x5b50, 0x5b9a, 0x5236, 0x7248, 0x672c))
foreach ($entry in @(@('Name', $editionName), @('Splash', 'WanZi Family'))) {
    $bitmap = [Drawing.Bitmap]::new(160, 24)
    $graphics = [Drawing.Graphics]::FromImage($bitmap)
    $font = [Drawing.Font]::new('Microsoft YaHei', 17, [Drawing.FontStyle]::Bold, [Drawing.GraphicsUnit]::Pixel)
    try {
        $graphics.Clear([Drawing.Color]::Black)
        $graphics.TextRenderingHint = [Drawing.Text.TextRenderingHint]::AntiAliasGridFit
        $format = [Drawing.StringFormat]::GenericTypographic
        $graphics.DrawString($entry[1], $font, [Drawing.Brushes]::White, 0, 0, $format)
        $width = [Math]::Min(160, [int][Math]::Ceiling($graphics.MeasureString($entry[1], $font, 160, $format).Width) + 2)
        [void]$output.AppendLine("inline constexpr int $($entry[0])Width = $width;")
        [void]$output.AppendLine("inline constexpr int $($entry[0])Height = 24;")
        [void]$output.AppendLine("inline constexpr uint8_t $($entry[0])Mask[] = {")
        for ($y = 0; $y -lt 24; $y++) {
            $row = for ($x = 0; $x -lt $width; $x++) { $bitmap.GetPixel($x, $y).R }
            [void]$output.AppendLine('    ' + ($row -join ',') + ',')
        }
        [void]$output.AppendLine('};')
    } finally {
        $font.Dispose()
        $graphics.Dispose()
        $bitmap.Dispose()
    }
}
[void]$output.AppendLine('}')
$target = Join-Path $PSScriptRoot '../../src/EditionBrandingAssets.h'
[IO.File]::WriteAllText([IO.Path]::GetFullPath($target), $output.ToString(), [Text.UTF8Encoding]::new($false))
